# Generated by Django 2.0 on 2017-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testColumn', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
