# Generated by Django 2.0 on 2017-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourProjectNo', models.CharField(max_length=50)),
                ('ourProjectNo', models.CharField(max_length=50)),
                ('yourRefPersonName', models.CharField(max_length=200)),
                ('ourRefPersonName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('addForMaterial', models.FloatField(default=1)),
                ('addForSubCon', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
